// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4GX2Y-nPn3n2q4xPORmPWZy_7UsJ10Y',
    appId: '1:567398402296:web:cc4fc318246091fd47930d',
    messagingSenderId: '567398402296',
    projectId: 'whatsapp-76658',
    authDomain: 'whatsapp-76658.firebaseapp.com',
    storageBucket: 'whatsapp-76658.appspot.com',
    measurementId: 'G-2ZE56RJVCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZY6vgGM0LcTXt90w2iBEDTgRrWeWO2p4',
    appId: '1:567398402296:android:8ed2d3adfe6b1e9d47930d',
    messagingSenderId: '567398402296',
    projectId: 'whatsapp-76658',
    storageBucket: 'whatsapp-76658.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC79MNuyxYiR3UpWlViQ0HQXCfPs9Nc3SE',
    appId: '1:567398402296:ios:58de27af39e315e647930d',
    messagingSenderId: '567398402296',
    projectId: 'whatsapp-76658',
    storageBucket: 'whatsapp-76658.appspot.com',
    iosClientId: '567398402296-egg2cc818vp59p888atcdcpgqh6p00ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC79MNuyxYiR3UpWlViQ0HQXCfPs9Nc3SE',
    appId: '1:567398402296:ios:58de27af39e315e647930d',
    messagingSenderId: '567398402296',
    projectId: 'whatsapp-76658',
    storageBucket: 'whatsapp-76658.appspot.com',
    iosClientId: '567398402296-egg2cc818vp59p888atcdcpgqh6p00ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsapp',
  );
}
